# Generated by Django 4.2.2 on 2023-06-28 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0002_alter_worker_position"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="is_complete",
        ),
        migrations.AddField(
            model_name="task",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="worker",
            name="position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="manager.position",
            ),
        ),
    ]
