# Generated by Django 4.2.2 on 2023-07-03 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0004_alter_task_assignees_alter_task_task_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("working", "Working"),
                            ("complete", "Complete"),
                            ("canceled", "Canceled"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "tasks",
                    models.ManyToManyField(
                        related_name="tasks", to="manager.task"
                    ),
                ),
            ],
        ),
    ]
