# Generated by Django 4.2.2 on 2023-07-03 20:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0005_project"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ("name", "status")},
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "members",
                    models.ManyToManyField(
                        related_name="members", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "projects",
                    models.ManyToManyField(
                        related_name="projects", to="manager.project"
                    ),
                ),
            ],
        ),
    ]
