# Generated by Django 4.2.2 on 2023-07-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0006_alter_project_options_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="tasks",
            field=models.ManyToManyField(
                related_name="projects", to="manager.task"
            ),
        ),
    ]
