# Generated by Django 4.2.2 on 2023-07-04 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0007_alter_project_tasks"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="tasks",
        ),
        migrations.RemoveField(
            model_name="team",
            name="projects",
        ),
        migrations.AddField(
            model_name="project",
            name="team",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="manager.team",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="task",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="manager.project",
            ),
            preserve_default=False,
        ),
    ]
