# Generated by Django 4.2.2 on 2023-07-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0008_remove_project_tasks_remove_team_projects_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="team",
        ),
        migrations.AddField(
            model_name="project",
            name="team",
            field=models.ManyToManyField(
                related_name="projects", to="manager.team"
            ),
        ),
    ]
