# Generated by Django 4.2.2 on 2023-07-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0009_remove_project_team_project_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("working", "Working"),
                    ("complete", "Complete"),
                    ("canceled", "Canceled"),
                ],
                default=("working", "Working"),
                max_length=15,
            ),
        ),
    ]
