# Generated by Django 4.2.2 on 2023-07-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0010_alter_project_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("working", "Working"),
                    ("completed", "Complete"),
                    ("canceled", "Canceled"),
                ],
                default=("working", "Working"),
                max_length=15,
            ),
        ),
    ]
